# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-01-09 15:22:35

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Ensure the Month column is datetime type
    data_raw['Month'] = pd.to_datetime(data_raw['Month'])

    # Create the line plot with smoothing
    fig = px.line(data_raw, x='Month', y='TotalSales', 
                  title='Total Sales Time Series',
                  template='plotly_white', 
                  line_shape='spline')  # Changed 'smooth' to 'spline'

    # Update the layout with specified details
    fig.update_layout(
        xaxis_title='Month',
        yaxis_title='Total Sales',
        title_font=dict(size=13.2),
        xaxis_tickfont=dict(size=8.8),
        yaxis_tickfont=dict(size=8.8),
        hoverlabel=dict(font=dict(size=8.8)),
        margin=dict(l=40, r=40, t=40, b=40)
    )
    
    # Update trace for line color and thickness
    fig.update_traces(line=dict(color='#3381ff', width=0.65))

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    
    return fig_dict