# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: sql_database_agent
# Time Created: 2025-01-02 13:06:53


def sql_database_pipeline(connection):
    import pandas as pd
    import sqlalchemy as sql
    
    # Create a connection if needed
    is_engine = isinstance(connection, sql.engine.base.Engine)
    conn = connection.connect() if is_engine else connection

    sql_query = '''
    SELECT 
    strftime('%Y', Orders.OrderDate) AS Year,
    Products.ProductName,
    SUM(OrderDetails.Quantity * OrderDetails.UnitPrice * (1 - OrderDetails.Discount)) AS TotalSales
FROM 
    Orders
JOIN 
    "Order Details" AS OrderDetails ON Orders.OrderID = OrderDetails.OrderID
JOIN 
    Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY 
    Year, Products.ProductName
ORDER BY 
    Year, Products.ProductName;
    '''
    
    return pd.read_sql(sql_query, connection)
        