# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: h2o_ml_agent
# Time Created: 2025-01-17 11:12:20

def h2o_automl(data_raw):
    import h2o
    from h2o.automl import H2OAutoML
    import pandas as pd



    # Initialize or connect to H2O if not already started
    h2o.init()

    # Convert the pandas DataFrame to an H2OFrame
    data_h2o = h2o.H2OFrame(data_raw)

    # Identify the target variable
    target = 'Churn'
    x = [col for col in data_h2o.columns if col != target]

    # Convert response variable to factor
    data_h2o[target] = data_h2o[target].asfactor()

    # Set parameters based on user instructions and recommendations
    aml = H2OAutoML(
        max_runtime_secs=30,  # User specified max runtime
        seed=42,
        nfolds=5,
        balance_classes=True,
        stopping_metric="AUC",
        sort_metric="AUC",
        exclude_algos=['DeepLearning'],
        max_models=20,
        stopping_rounds=5,
        verbosity="info"
    )

    # Train the AutoML model
    aml.train(x=x, y=target, training_frame=data_h2o)

    # Determine model saving logic
    model_directory = "/Users/mdancho/Desktop/course_code/free-ai-tips/009_h2o_machine_learning_agent/h2o_models/"
    log_path = "/Users/mdancho/Desktop/course_code/free-ai-tips/009_h2o_machine_learning_agent/ai_functions/"
    
    if model_directory is None and log_path is None:
        model_path = None
    else:
        path_to_save = model_directory if model_directory is not None else log_path
        model_path = h2o.save_model(model=aml.leader, path=path_to_save, force=True)

    return dict(
        leaderboard=aml.leaderboard.as_data_frame().to_dict(),
        best_model_id=aml.leader.model_id,
        model_path=model_path,
    )